baseURL = 'https://damondb.github.io/hugo-damon-db/'
languageCode = 'en-us'
title = 'DAMON 2023 workshop'

disableKinds = ["taxonomy", ]

[params]
# Optional change logo file
  [params.logo]
    small = "logo/DaMon_logo.png"
#    large = "logo/DaMon_logo_20yrs.png"
  [params.banner]
    image = "img/title_Seattle_panorama.jpg"
    [[params.banner.sponsors]]
      name = "SAP"
      file = "img/sap_logo.png"
      style = "max-width: 400px"
  [params.workshop]
    number = 19
    title = "Data Management on New Hardware (DaMoN)"
    date = "Monday June 19, 2023"
    submission = "March 24th, 2024"
    notification = "April 28th, 2024"
  [params.conference]
    title = "ACM SIGMOD/PODS"
    link = "https://2023.sigmod.org/"
    year = 2023
    location = "Seattle, WA, USA" 

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true # default is false
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.image]
        enableDefault = true
        errorLevel = 'warning' # ignore (default), warning, or error (fails the build)

[module]
  [[module.imports]]
    path = "github.com/damondb/hugo-damon-db"

[build]
  writeStats = true